spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8

server:
  port: 8100
  compression:
    enabled: true
  servlet:
    context-path: /


#日志
logging:
  level:
    ROOT: error
    net.xuanyutech.app.test.zktest.app: debug




